- hosts: localhost
  roles:
     - osp-workstation
     - osp-network
     - osp-keypair
     - osp-securitygroup
  tasks:
##Create Fronend Instance
  - name: Create frontend instance
    include_role:
       name: osp-instances
       vars_from: frontend.yaml
###Create App1 server 
  - name: Create app2 instance
    include_role:
       name: osp-instances
       vars_from: app1.yaml
##Create App2 server
  - name: Create app2 instance
    include_role:
       name: osp-instances
       vars_from: app2.yaml
##Create DB server
  - name: Create db instance
    include_role:
       name: osp-instances
       vars_from: db.yaml
## Alternate Method to create dynmaic inventory
  - name: Gather facts
    include_role: 
       name: osp-facts
  - name: Wait for "{{ instance_name }}" to be available
    wait_for:
      host: 10.10.10.3
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost


###Configuration on OSP Instances

- hosts: apps
  gather_facts: false
  become: yes
  tasks:
  - name: Ping
    ping:
