- hosts: localhost
  roles:
     - osp-workstation
     - osp-network
     - osp-keypair
  tasks:
  - name: Create frontend instance
    include_role:
       name: osp-instances
       vars_from: frontend.yaml
